services:
  postgres-db:
    image: 'postgres:latest'
    env_file: '.env'
    environment:
      POSTGRES_DB: '${POSTGRES_DB}'
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
    ports:
      - '5433:5432'
    volumes:
      - 'postgres_volume:/var/lib/postgresql/data'

volumes:
  postgres_volume:
