spring:
  config:
    import: env.yml
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${USER_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    baseline-on-migrate: true
    enabled: true